### ISSUE TITLE
Where is the Dockerfile?

### ISSUE THREAD

**Issue by Korri** [claytondukes/autogpt-docker#2]
It's generally good practice to make the file that is used to build an image (in this case `cdukes/autogpt-gotty` open source, so that it can be audited, and improved upon!

**Comment by claytondukes** [comment]
It's on [docker hub](https://hub.docker.com/repository/docker/cdukes/autogpt-gotty/tags?page=1&ordering=last_updated).

**Comment by claytondukes** [comment]
I've added the source Dockerfile to the repo. Sorry about that.
