### ISSUE TITLE
Connection closed by an error: failed to create backend:

### ISSUE THREAD

**Issue by Korri** [claytondukes/autogpt-docker#3]
Trying to use this, when I connect to the web interfaced I get the following error:

> Connection closed by an error: failed to create backend: failed to start command `bash`: exec: "bash": executable file not found in $PATH

Is `bash` missing in the container maybe?

**Comment by claytondukes** [comment]
That's an auto-gpt issue. It is trying to execute a shell command and is unable to. Do you have shell commands enabled?

**Comment by moltra** [comment]
I am having the same error.  I installed the docker as designed.

**Comment by claytondukes** [comment]
Please check the README on this repo. It's unlikely my docker compose will work anymore. They are making too many changes too fast.
