### ISSUE TITLE
error when trying to start docker

### ISSUE THREAD

**Issue by moltra** [claytondukes/autogpt-docker#4]
Connection closed by an error: failed to create backend: failed to start command `bash`: exec: "bash": executable file not found in $PATH:

Ubuntu 22.04

**Comment by Korri** [comment]
Same as https://github.com/claytondukes/autogpt-docker/issues/3 ? Might be that default configuration will try to use bash.

**Comment by claytondukes** [comment]
Most likely. Also please check the README on this repo. It's unlikely my docker compose will work anymore. They are making too many changes too fast.
